feat: modularise install configs

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,9 +2,20 @@
 
 set -e
 
-CONFIG="install.conf.yaml"
-DOTBOT_DIR="dotbot"
+if [ "$1" = "base" ]; then
+    CONFIG="install-base.conf.yaml"
+elif [ "$1" = "ubuntu" ]; then
+    CONFIG="install-ubuntu.conf.yaml"
+elif [ "$1" = "dotnet" ]; then
+    CONFIG="install-dotnet.conf.yaml"
+elif [ "$1" = "wsl" ]; then
+    CONFIG="install-wsl.conf.yaml"
+else
+     echo "Missing argument"
+     exit 1
+fi
 
+DOTBOT_DIR="dotbot"
 DOTBOT_BIN="bin/dotbot"
 BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
@@ -12,4 +23,4 @@ cd "${BASEDIR}"
 git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
 git submodule update --init --recursive "${DOTBOT_DIR}"
 
-"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
+"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}"
